# Generated by Django 3.0 on 2019-12-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Nomer_Telepon', models.CharField(max_length=12)),
                ('Bidang', models.CharField(max_length=200)),
                ('Jadwal_Praktek', models.DateTimeField(verbose_name='jadwal praktek')),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Kandungan', models.CharField(max_length=200)),
                ('Khasiat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Nomer_telepon', models.CharField(max_length=12)),
                ('Alamat', models.CharField(max_length=200)),
                ('Keluhan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Total_Harga', models.PositiveIntegerField(default=0)),
                ('Kumpulan_Obat', models.CharField(max_length=200)),
            ],
        ),
    ]
