# Generated by Django 3.0 on 2019-12-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasien',
            old_name='Nomer_telepon',
            new_name='Nomer_Telepon',
        ),
    ]
