# Generated by Django 3.0 on 2019-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20191209_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obat',
            name='Khasiat',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='Keluhan',
            field=models.TextField(max_length=200),
        ),
    ]
