# Generated by Django 3.0 on 2019-12-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20191209_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokter',
            name='Nomer_Telepon',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='Nomer_Telepon',
        ),
        migrations.AddField(
            model_name='dokter',
            name='Nomor_Telepon',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pasien',
            name='Nomor_Telepon',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='Bidang',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='Nama',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='Alamat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='Keluhan',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='Nama',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resep',
            name='Kumpulan_Obat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resep',
            name='Nama',
            field=models.CharField(default='', max_length=200),
        ),
    ]
