# Generated by Django 3.0 on 2019-12-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Species', models.CharField(max_length=12)),
                ('Berat', models.IntegerField(default=0)),
                ('Umur', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Isi_Kandang', models.PositiveSmallIntegerField(default=0)),
                ('Luas_Kandang', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Nomer_Telepon', models.CharField(max_length=12)),
                ('Hari_Berkunjung', models.DateTimeField(verbose_name='Hari Berkunjung')),
            ],
        ),
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Nomer_Telepon', models.CharField(max_length=12)),
                ('Jadwal_Jaga', models.DateTimeField(verbose_name='Jadwal Jaga')),
            ],
        ),
    ]
