# Generated by Django 3.0 on 2019-12-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandang',
            name='Luas_Kandang',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
