# Generated by Django 3.0 on 2019-12-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0002_auto_20191209_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kandang',
            name='Isi_Kandang',
        ),
    ]
