# Generated by Django 3.0 on 2019-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoo', '0003_remove_kandang_isi_kandang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengunjung',
            old_name='Nomer_Telepon',
            new_name='Nomor_Telepon',
        ),
        migrations.RenameField(
            model_name='penjaga',
            old_name='Nomer_Telepon',
            new_name='Nomor_Telepon',
        ),
        migrations.AddField(
            model_name='kandang',
            name='Isi_Kandang',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='Nama',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hewan',
            name='Species',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='kandang',
            name='Nama',
            field=models.CharField(default='', max_length=200),
        ),
    ]
